config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "expenses#index"
  resources :expenses
  resources :incomes, except: [:index]
  resources :users, only: :show do
    member do
      get 'expense_chart'
      get 'income_chart'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
	extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :expense_item
	belongs_to :user
	validates :expense_item_id, presence: true
	validates :price, presence: true

	class << self
    def expense_name #グラフに渡すハッシュデータを形成するメソッド
      expenses = all
      expense_data = {}
    	expenses.each_with_index do |expense, index|
        expense_data = { expense.expense_item.name => 1 } if index.zero? #eachでDBから取得したデータを回し、既に、keyとして存在しているかをチェックする
        if expense_data.key?(expense.expense_item.name) #もう既に存在していれば割合の基準となるvalueに1を足していく
          expense_data[expense.expense_item.name] += 1
        else
          expense_data[expense.expense_item.name] = 1
        end
      end
      expense_data
    end
	end
end

app/models/expense_item.rb
class  ExpenseItem < ActiveHash::Base
  self.data = [
      {id: 1, name: "住居費"}, {id: 2, name: "水道光熱費"}, {id: 3, name: "通信費"},
			{id: 4, name: "保険料"}, {id: 5, name: "食費"}, {id: 6, name: "日用品費"},
			{id: 7, name: "被服費"}, {id: 8, name: "美容費"}, {id: 9, name: "交際費"},
			{id: 10, name: "医療費"}, {id: 11, name: "特別費"}, {id: 12, name: "雑費"}
  ]
end

app/models/income.rb
class Income < ApplicationRecord
	extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :income_item
	belongs_to :user
	validates :income_item_id, presence: true
	validates :price, presence: true

	class << self
    def income_name #グラフに渡すハッシュデータを形成するメソッド
      incomes = all
      income_data = {}
    	incomes.each_with_index do |income, index|
        income_data = { income.income_item.name => 1 } if index.zero? #eachでDBから取得したデータを回し、既に、keyとして存在しているかをチェックする
        if income_data.key?(income.income_item.name) #もう既に存在していれば割合の基準となるvalueに1を足していく
          income_data[income.income_item.name] += 1
        else
          income_data[income.income_item.name] = 1
        end
      end
      income_data
    end
	end
end

app/models/income_item.rb
class  IncomeItem < ActiveHash::Base
  self.data = [
      {id: 1, name: "給料"}, {id: 2, name: "残業代"}, {id: 3, name: "ボーナス"},
			{id: 4, name: "出張旅費"}, {id: 5, name: "その他の手当て"}, {id: 6, name: "健康保険給付金"},
			{id: 7, name: "懸賞金"}, {id: 8, name: "サイドビジネス"}, {id: 9, name: "児童手当"},
			{id: 10, name: "受贈品"}, {id: 11, name: "所得税還付金"}, {id: 12, name: "その他"},
			{id: 13, name: "受取利息"}, {id: 14, name: "配当金"}, {id: 15, name: "売却損益"}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :expenses
  has_many :incomes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name])
	end
end

app/controllers/expense_controller.rb
class ExpenseController < ApplicationController
	def index
	end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
	before_action :set_expense, only: [:show, :edit, :update, :destroy]

	def index
		if user_signed_in?
			@user_expenses = current_user.expenses
			@user_incomes = current_user.incomes
			@expenses = @user_expenses.order(created_at: "DESC").limit(4)
			@incomes = @user_incomes.order(created_at: "DESC").limit(4)
		end
	end

	def new
		@expense = Expense.new
	end

	def create
		@expense = Expense.new(params_expense)
		if @expense.valid?
			@expense.save
			redirect_to root_path
		else
			render "new"
		end
	end

	def show
	end

	def edit
		redirect_to root_path unless @expense.user_id == current_user.id
	end

	def update
		if @expense.update(params_expense)
			redirect_to root_path
		else
			render "edit"
		end
	end

	def destroy
		@expense.delete if @expense.user_id == current_user.id
		redirect_to root_path
	end

	private

	def params_expense
		params.require(:expense).permit(:expense_item_id, :price, :memo).merge(user_id: current_user.id)
	end

	def set_expense
		@expense = Expense.find(params[:id])
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	before_action :set_income, only: [:show, :edit, :update, :destroy]

	def new
		@income = Income.new
	end

	def create
		@income = Income.new(params_income)
		if @income.valid?
			@income.save
			redirect_to root_path
		else
			render "new"
		end
	end

	def show
	end

	def edit
		redirect_to root_path unless @income.user_id == current_user.id
	end

	def update
		if @income.update(params_income)
			redirect_to root_path
		else
			render "edit"
		end
	end

	def destroy
		@income.delete if @income.user_id == current_user.id
		redirect_to root_path
	end

	private

	def params_income
		params.require(:income).permit(:income_item_id, :price, :memo).merge(user_id: current_user.id)
	end

	def set_income
		@income = Income.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		expenses = current_user.expenses
		@expense_sum_price = expenses.all.sum(:price)
		incomes = current_user.incomes
		@income_sum_price = incomes.all.sum(:price)
		@total_amount = @income_sum_price - @expense_sum_price
	end

	def expense_chart
		@expense_data = Expense.expense_name
	end

	def income_chart
		@income_data = Income.income_name
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/edit.html.erb
<h1>支出編集</h1>
<%= form_with model: @expense, method: :patch, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
	<div class="row">
		<div class="col s12">
			<div class="row">
				<div class="col s2">
					<div class="list-items">費目</div>
					<%= f.collection_select :expense_item_id, ExpenseItem.all, :id, :name, { prompt: "選択してください" }, { class: "select-item" } %>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<div class="list-items">金額</div>
					<%= f.text_field :price, id: "input_text" %>
				</div>
			</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<div class="list-items">メモ</div>
					<%= f.text_area :memo, id: "textarea2", class: "materialize-textarea" %>
				</div>
			</div>
		</div>
	</div>
	<div class="input-field col s6">
    <%= f.submit "編集" %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<% if user_signed_in? %>
	<%= link_to "支出登録", new_expense_path, class: "waves-effect waves-light btn-large" %>
	<%= link_to "収入登録", new_income_path, class: "waves-effect waves-light btn-large" %>
	<%= link_to "マイページ", user_path(current_user.id), class: "waves-effect waves-light btn-large" %>
	<h4><%= current_user.nickname %>さんの支出一覧</h4>
	<% if @expenses.present? %>
		<div class="row">
			<% @expenses.each do |expense| %>
				<div class="col s12 m3">
					<div class="card blue-grey lighten-5">
						<div class="card-content black-text">
							<span class="card-title">登録日:<%= expense.created_at.strftime("%Y年%m月%d日") %></span>
							<span class="card-title">登録者:<%= expense.user.nickname %></span>
							<span class="card-title">費目:<%= expense.expense_item.name %></span>
							<span class="card-title">金額:¥<%= expense.price.to_s(:delimited, delimiter: ',') %></span>
							<span class="card-title">メモ:<%= expense.memo %></span>
						</div>
						<div class="card-action">
							<%= link_to "詳細", expense_path(expense.id) %>
						</div>
					</div>
				</div>
			<% end %>
	<% else %>
		<p>登録されている支出はありません。</p>
	<% end %>
	</div>
	<h4><%= current_user.nickname %>さんの収入一覧</h4>
	<% if @incomes.present? %>
		<div class="row">
			<% @incomes.each do |income| %>
				<div class="col s12 m3">
					<div class="card blue-grey lighten-5">
						<div class="card-content black-text">
							<span class="card-title">登録日:<%= income.created_at.strftime("%Y年%m月%d日") %></span>
							<span class="card-title">登録者:<%= income.user.nickname %></span>
							<span class="card-title">費目:<%= income.income_item.name %></span>
							<span class="card-title">金額:¥<%= income.price.to_s(:delimited, delimiter: ',') %></span>
							<span class="card-title">メモ:<%= income.memo %></span>
						</div>
						<div class="card-action">
							<%= link_to "詳細", income_path(income.id) %>
						</div>
					</div>
				</div>
			<% end %>
	<% else %>
		<p>登録されている収入はありません。</p>
	<% end %>
	</div>
<% end %>

app/views/expenses/new.html.erb
<h1>支出登録</h1>
<%= form_with model: @expense, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
	<div class="row">
		<div class="col s2">
			<div class="list-items">費目</div>
			<%= f.collection_select :expense_item_id, ExpenseItem.all, :id, :name, { prompt: "選択してください" }, { class: "select-item" } %>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
			<%= f.text_field :price, id: "input_text" %>
			<%= f.label :price, id: "input_text" %>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
			<%= f.text_area :memo, id: "textarea2", class: "materialize-textarea" %>
			<%= f.label :memo, for: "textarea2" %>
		</div>
	</div>
	<div class="input-field col s6">
    <%= f.submit "新規登録" %>
  </div>
<% end %>

app/views/expenses/show.html.erb
<h4><%= @expense.user.nickname %>さん</h4>
<h5><%= @expense.created_at.strftime("%Y年%m月%d日") %>の支出詳細</h5>
<div class="row">
	<div class="col s12 m3">
		<div class="card blue-grey lighten-5">
			<div class="card-content black-text">
				<span class="card-title">登録日:<%= @expense.created_at.strftime("%Y年%m月%d日") %></span>
				<span class="card-title">登録者:<%= @expense.user.nickname %></span>
				<span class="card-title">費目:<%= @expense.expense_item.name %></span>
				<span class="card-title">金額:¥<%= @expense.price.to_s(:delimited, delimiter: ',') %></span>
				<span class="card-title">メモ:<%= @expense.memo %></span>
			</div>
			<div class="card-action">
				<%= link_to "編集", edit_expense_path(@expense.id) %>
				<%= link_to "削除", expense_path(@expense.id), method: :delete %>
			</div>
		</div>
	</div>
</div>

app/views/incomes/edit.html.erb
<h1>収入編集</h1>
<%= form_with model: @income, method: :patch, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
	<div class="row">
		<div class="col s12">
			<div class="row">
				<div class="col s2">
					<div class="list-items">費目</div>
					<%= f.collection_select :income_item_id, ExpenseItem.all, :id, :name, { prompt: "選択してください" }, { class: "select-item" } %>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<div class="list-items">金額</div>
					<%= f.text_field :price, id: "input_text" %>
				</div>
			</div>
			</div>
			<div class="row">
				<div class="input-field col s6">
					<div class="list-items">メモ</div>
					<%= f.text_area :memo, id: "textarea2", class: "materialize-textarea" %>
				</div>
			</div>
		</div>
	</div>
	<div class="input-field col s6">
    <%= f.submit "編集" %>
  </div>
<% end %>

app/views/incomes/new.html.erb
<h1>収入登録</h1>
<%= form_with model: @income, local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
	<div class="row">
		<div class="col s2">
			<div class="list-items">費目</div>
			<%= f.collection_select :income_item_id, IncomeItem.all, :id, :name, { prompt: "選択してください" }, { class: "select-item" } %>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
			<%= f.text_field :price, id: "input_text" %>
			<%= f.label :price, id: "input_text" %>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
			<%= f.text_area :memo, id: "textarea2", class: "materialize-textarea" %>
			<%= f.label :memo, for: "textarea2" %>
		</div>
	</div>
	<div class="input-field col s6">
    <%= f.submit "新規登録" %>
  </div>
<% end %>

app/views/incomes/show.html.erb
<h4><%= @income.user.nickname %>さん</h4>
<h5><%= @income.created_at.strftime("%Y年%m月%d日") %>の収入詳細</h5>
<div class="row">
	<div class="col s12 m3">
		<div class="card blue-grey lighten-5">
			<div class="card-content black-text">
				<span class="card-title">登録日:<%= @income.created_at.strftime("%Y年%m月%d日") %></span>
				<span class="card-title">登録者:<%= @income.user.nickname %></span>
				<span class="card-title">費目:<%= @income.income_item.name %></span>
				<span class="card-title">金額:¥<%= @income.price.to_s(:delimited, delimiter: ',') %></span>
				<span class="card-title">メモ:<%= @income.memo %></span>
			</div>
			<div class="card-action">
				<%= link_to "編集", edit_income_path(@income.id) %>
				<%= link_to "削除", income_path(@income.id), method: :delete %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>シンプル家計簿アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "シンプル家計簿", root_path, class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>

  </body>
</html>

app/views/users/expense_chart.html.erb
<h4><%= current_user.nickname %>さんの支出推移</h4>
<%= pie_chart @expense_data %>

app/views/users/income_chart.html.erb
<h4><%= current_user.nickname %>さんの収入推移</h4>
<%= pie_chart @income_data %>

app/views/users/show.html.erb
<h4><%= current_user.nickname %>さんの支出合計</h4>
<div class="row">
	<div class="col s12 m4">
		<div class="card blue-grey lighten-5">
			<div class="card-content black-text">
				<span class="card-title">今月の支出合計</span>
				<span class="card-title">¥<%= @expense_sum_price %></span>
			</div>
			<div class="card-action">
				<%= link_to "グラフで見る", expense_chart_user_path %>
			</div>
		</div>
	</div>
</div>

<h4><%= current_user.nickname %>さんの収入合計</h4>
<div class="row">
	<div class="col s12 m4">
		<div class="card blue-grey lighten-5">
			<div class="card-content black-text">
				<span class="card-title">今月の収入合計</span>
				<span class="card-title">¥<%= @income_sum_price %></span>
			</div>
			<div class="card-action">
				<%= link_to "グラフで見る", income_chart_user_path %>
			</div>
		</div>
	</div>
</div>
<h4><%= current_user.nickname %>さんの収支合計</h4>
<% if @income_sum_price > @expense_sum_price %>
	<div class="row">
		<div class="col s12 m4">
			<div class="card blue-grey lighten-5">
				<div class="card-content black-text">
					<span class="card-title">今月の収支</span>
					<span class="card-title">+<%= @total_amount %></span>
				</div>
			</div>
		</div>
	</div>
<% else %>
	<div class="row">
		<div class="col12 m4">
			<div class="card blue-grey lighten-5">
				<div class="card-content black-text">
					<span class="card-title">今月の収支</span>
					<span class="card-title">-<%= @total_amount %></span>
				</div>
			</div>
		</div>
	</div>
<% end %>